# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171109_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='studentid',
        ),
        migrations.AddField(
            model_name='profile',
            name='groupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Group'),
        ),
    ]
