# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171109_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprocedure',
            name='procedurename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labprocedure',
            name='sensorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Sensors'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.StudentGroup'),
        ),
    ]
