# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_datavalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProcedureStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.StudentGroup')),
                ('procedureid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.LabProcedure')),
            ],
        ),
        migrations.AddField(
            model_name='labactivity',
            name='numprocedures',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
