# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_labprocedure_procedurestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labactivity',
            name='hidden',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='labactivity',
            name='selected',
            field=models.BooleanField(),
        ),
    ]
