# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20171114_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loggedin',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
