# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_loggedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facultyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Faculty'),
            preserve_default=False,
        ),
    ]
