# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_labprocedurestatus_labid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='value',
            field=models.CharField(max_length=10000),
        ),
    ]
