# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_groupgrade_labid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprocedurestatus',
            name='status',
        ),
        migrations.AddField(
            model_name='groupgrade',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
