# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20171123_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprocedurestatus',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
