# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_labprocedurestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgrade',
            name='value',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
