# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgrade',
            name='average',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
