# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_groupgrade_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgrade',
            name='average',
            field=models.FloatField(null=True),
        ),
    ]
